fz152_contact.settings.*:
  type: config_object
  mapping:
    bundle:
      type: string
      label: 'Contact bundle'
    contact:
      type: fz152_contact.contact.[%parent.bundle]
    enabled:
      type: boolean
      label: 'Enabled'
      translatable: true
    weight:
      type: integer
      label: 'Weight'
      translatable: true
    langcode:
      type: string
      label: 'Language code'
