fz152.settings:
  type: config_object
  label: 'FZ152 — settings'
  mapping:
    langcode:
      type: string
      label: 'Language code'
    enable:
      type: boolean
      label: 'Enable functionality'
      translatable: true
    is_checkbox:
      type: boolean
      label: 'Show with checkbox'
      translatable: true
    checkbox_title:
      type: text
      lalbel: 'Checkbox label'

fz152.privacy_policy_page:
  type: config_object
  label: 'FZ152 — privacy policy page'
  mapping:
    langcode:
        type: string
        label: 'Language code'
    enable:
      type: boolean
      label: 'Enable privacy policy page'
      translatable: true
    title:
      type: string
      label: 'Page title'
      translatable: true
    path:
      type: string
      label: 'Page path'
      translatable: true
    text:
      type: mapping
      label: 'Page text'
      mapping:
        value:
          type: text
          label: 'Value'
        format:
          type: string
          label: 'Filter'

fz152.forms:
  type: config_object
  label: 'FZ152 — forms'
  mapping:
    langcode:
      type: string
      label: 'Language code'
    forms:
      type: text
      label: 'Forms'