<?php

namespace Drupal\fz152\Plugin\Fz152;

use Drupal\fz152\Annotation\Fz152;
use Drupal\fz152\Fz152PluginBase;

/**
 * @Fz152(
 *   id = "forms",
 * )
 */
class Forms extends Fz152PluginBase {

  /**
   * {@inheritdoc}
   */
  public function getSettingsPage() {
    return [
      'path' => 'forms',
      'title' => 'Forms',
      'form' => '\Drupal\fz152\Form\Fz152SettingsForms',
      'weight' => 0,
    ];
  }

  public function getForms() {
    return parent::getForms(); // TODO: Change the autogenerated stub
  }
}
